### ISSUE TITLE
Migrate to OCP4

### ISSUE THREAD

**Issue by esune** [bcgov/law-society-demo#36]
The app deployments need to be migrated to OCP4.

No special security policies are required, other than allowing ingress to the app's route, as this is a self-contained SPA.

Please deploy `dev` and `test` instances (no `prod`, see the param files already available) in our shared demo namespace `a99fd4`.

Once the apps have been deployed, please coordinate with me to update the settings in the relevant Keycloak realms.

**Comment by wadeking98** [comment]
up and running in dev and test
